export const ApiConstants = {
  API_USER_FAIL: "API_USER_FAIL",
  API_SERVER_ERROR: "API_SERVER_ERROR",

  API_LOGIN_LOAD: "LOGIN_LOAD",
  API_LOGIN_SUCCESS: "LOGIN_SUCCESS",

  API_LOGOUT_LOAD: "API_LOGOUT_LOAD",
  API_LOGOUT_SUCCESS: "API_LOGOUT_SUCCESS",

  API_GET_ALL_USER_LOAD: "API_GET_ALL_USER_LOAD",
  API_GET_ALL_USER_SUCCESS: "API_GET_ALL_USER_SUCCESS",

  API_DELETE_USER_LOAD: "API_DELETE_USER_LOAD",
  API_DELETE_USER_SUCCESS: "API_DELETE_USER_SUCCESS",

  API_CREATE_USER_LOAD: "API_CREATE_USER_LOAD",
  API_CREATE_USER_SUCCESS: "API_CREATE_USER_SUCCESS",

  API_EDIT_USER_LOAD: "API_EDIT_USER_LOAD",
  API_EDIT_USER_SUCCESS: "API_EDIT_USER_SUCCESS",
};
